import { Metadata } from "next";
import "./globals.css";
import App from './components/App';
import { StoreProvider } from '@/redux/StoreProvider';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';

export const metadata: Metadata = {
  title: "HG-Fashion-Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
         
          <StoreProvider>
            <App>{children}</App>
          </StoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
